openapi: 3.0.1
info:
  contact:
    email: lampralexandros@gmail.com
  description: This is a sample openApi document
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: https://wabli.netlify.app/
  title: TempApi
  version: 1.0.0
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
- description: local-host
  url: http://localhost:8090/v1
security:
- {}
tags:
- description: not yet ready
  name: course
paths:
  /course:
    post:
      operationId: createcourse
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/course'
        description: data to be created
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/course'
          description: successful operation
      summary: Creates the data
      tags:
      - course
      x-eov-operation-handler: controllers/CourseController
  /course/{courseId}:
    delete:
      operationId: deletecourse
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: courseId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          description: successful operation
      summary: Delete the element
      tags:
      - course
      x-eov-operation-handler: controllers/CourseController
    get:
      operationId: getcourse
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: courseId
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/course'
          description: successful operation
      summary: Get the element
      tags:
      - course
      x-eov-operation-handler: controllers/CourseController
    put:
      operationId: updatecourse
      parameters:
      - description: the Id parameter
        explode: false
        in: path
        name: courseId
        required: true
        schema:
          type: string
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/course'
        description: data to be updated
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/course'
          description: successful operation
      summary: Updates the element
      tags:
      - course
      x-eov-operation-handler: controllers/CourseController
  /course/getAll:
    get:
      operationId: getAllcourse
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/course'
                type: array
          description: successful operation
      summary: Get all the data
      tags:
      - course
      x-method-getAll: "true"
      x-eov-operation-handler: controllers/CourseController
components:
  schemas:
    course:
      example:
        courseTitle: courseTitle
        courseImage:
          data: data
          name: name
        courseDate: courseDate
        _id: _id
        courseDescription: courseDescription
      properties:
        _id:
          type: string
        courseTitle:
          type: string
        courseImage:
          $ref: '#/components/schemas/course_courseImage'
        courseDescription:
          type: string
        courseDate:
          type: string
      required:
      - courseDate
      - courseDescription
      - courseImage
      - courseTitle
      type: object
    course_courseImage:
      example:
        data: data
        name: name
      properties:
        data:
          type: string
        name:
          type: string
      type: object
      x-isSchemaOnly: "true"
